import React, { Component } from 'react'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }
  
export class HealthBot extends Component {
  render() {
    return (
      <div>
        <iframe width="350" height="430" allow="microphone;" src="https://console.dialogflow.com/api-client/demo/embedded/8a052415-abf8-47d5-b18f-59d6589fbc6c"></iframe>

      </div>
    )
  }
}

export default HealthBot
